name = "deSolveDiffEq"
uuid = "0518478a-701b-4815-806c-24ad5cb92f09"
authors = ["Chris Rackauckas <accounts@chrisrackauckas.com>"]
version = "1.0.0"

[deps]
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
RCall = "6f49c342-dc21-5d91-9882-a32aef131414"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
DiffEqBase = "6"
PrecompileTools = "1"
RCall = "0.14"
Reexport = "1.0"
julia = "1.10"

[extras]
AllocCheck = "9b6a8646-10ed-4001-bbdc-1d2f46dfbb1a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["AllocCheck", "Test"]
